### ISSUE TITLE
Version 0.4 breaks "calc" functions when compiling

### ISSUE THREAD

**Issue by dkrutsko** [sylvainbaronnet/postcss-position-alt#1]
Hey there, Using 0.4.0 broke `top: calc(100% + 5px);` by transforming it to `top: calc(100%; +: 5px);`. Downgrading to version 0.3.0 fixed this problem. Could you please verify the error? Also, are there changelogs anywhere?

**Comment by sylvainbaronnet** [comment]
Hi dkrutsko,

Thanks for pointing this out. 
In 0.4.0 I added shortcut for top, left, bottom, right and z-index (`top: 1px left 12px z-index 9` for example)
I updated the Readme, I should have a Changelog...

I parse values by spliting space, that's why there's this problem. I think I could fix this by replacing ` + ` with `+` before parsing values, and replacing back after ?
I will try to fix this and add some test for this case.

**Comment by sylvainbaronnet** [comment]
I published a new version that fix it.
There's a bunch of test to cover this case : https://github.com/sylvainbaronnet/postcss-position-alt/blob/master/test/test.js#L132 so this should be fixed for most case.

And there's a changelog now : https://github.com/sylvainbaronnet/postcss-position-alt/blob/master/CHANGELOG.md
